server:
  port: 9527
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://120.78.123.215:3316/piproject?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  application:
    name: pitools
  profiles:
    active: dev

pi:
  fileSavePath: /Users/jaygoaler/project