server:
  port: 9527
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://139.155.49.170:3316/piproject?useUnicode=true&characterEncoding=utf8
    username: pi
    password: yangjie
  application:
    name: pitools
  profiles:
    active: dev
  freemarker:
    charset: UTF-8
    default_encoding: UTF-8
    expose-session-attributes: true
    content-type: text/html;charset=UTF-8
    suffix: .html
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/static/,classpath:/static/,classpath:/public

pi:
  fileSavePath: D:\Recive\uploadFiles
  ftp:
    #ftp服务器的地址
    host: jaygoaler.xyz
    #ftp服务器的端口号（连接端口号）
    port: 21
    #ftp的用户名
    userName: ftp_jay
    #ftp的密码
    password: yangjie520
    #ftp上传的根目录
    basePath: /home/data/jay
    #回显地址
    httpPath:


## /Users/jaygoaler/project